name: 🔒 Security Vulnerability
description: Report a security vulnerability (Please use private reporting for sensitive issues)
title: "[SECURITY]: "
labels: ["security", "critical"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        ⚠️ **IMPORTANT**: For sensitive security vulnerabilities, please use GitHub's private vulnerability reporting feature instead of creating a public issue.
        
        Go to the Security tab > Report a vulnerability to report privately.

  - type: checkboxes
    id: security-checks
    attributes:
      label: Security Report Checklist
      description: Please confirm the following before proceeding
      options:
        - label: This is NOT a sensitive security vulnerability that could be exploited if made public
          required: true
        - label: I have verified this issue exists in the latest version
          required: true
        - label: I have not attempted to exploit this vulnerability maliciously
          required: true

  - type: dropdown
    id: vulnerability-type
    attributes:
      label: 🔐 Vulnerability Type
      description: What type of security issue is this?
      options:
        - Authentication/Authorization Issue
        - Input Validation/Injection
        - Cross-Site Scripting (XSS)
        - Cross-Site Request Forgery (CSRF)
        - Information Disclosure
        - Cryptographic Issue
        - Session Management
        - API Security Issue
        - Configuration/Deployment Issue
        - Dependency Vulnerability
        - Other (specify below)
    validations:
      required: true

  - type: dropdown
    id: severity-assessment
    attributes:
      label: 📊 Severity Assessment
      description: How severe do you believe this vulnerability is?
      options:
        - Critical (Remote code execution, full system compromise)
        - High (Significant data exposure, privilege escalation)
        - Medium (Limited data exposure, partial access)
        - Low (Information disclosure, minor security issue)
        - Informational (Security best practices, hardening)
    validations:
      required: true

  - type: textarea
    id: vulnerability-description
    attributes:
      label: 🔍 Vulnerability Description
      description: Provide a clear description of the security issue
      placeholder: |
        Describe the vulnerability:
        - What component is affected?
        - How does the vulnerability work?
        - What are the potential impacts?
    validations:
      required: true

  - type: textarea
    id: affected-components
    attributes:
      label: 🎯 Affected Components
      description: Which parts of Source License are affected?
      placeholder: |
        - API endpoints: /api/...
        - Admin interface: /admin/...
        - Authentication system
        - Database models
        - Configuration files
        - Dependencies
    validations:
      required: true

  - type: textarea
    id: reproduction-steps
    attributes:
      label: 🔬 Steps to Reproduce
      description: Provide steps to reproduce the vulnerability (if safe to share publicly)
      placeholder: |
        1. Set up Source License with default configuration
        2. Navigate to [specific page/endpoint]
        3. Perform [specific action]
        4. Observe [security issue]
        
        NOTE: If steps could be used maliciously, consider private reporting instead.
    validations:
      required: true

  - type: textarea
    id: proof-of-concept
    attributes:
      label: 💻 Proof of Concept
      description: Provide a safe proof of concept (remove sensitive details)
      placeholder: |
        Include code snippets, HTTP requests, or other evidence:
        - Sanitize any sensitive information
        - Remove actual credentials or tokens
        - Focus on demonstrating the issue safely
      render: shell
    validations:
      required: false

  - type: textarea
    id: impact-assessment
    attributes:
      label: 💥 Impact Assessment
      description: What are the potential impacts of this vulnerability?
      placeholder: |
        - Data that could be exposed
        - Systems that could be compromised
        - Users who could be affected
        - Business operations that could be impacted
    validations:
      required: true

  - type: textarea
    id: mitigation-suggestions
    attributes:
      label: 🛡️ Suggested Mitigation
      description: Do you have suggestions for fixing this vulnerability?
      placeholder: |
        - Input validation improvements
        - Authentication/authorization changes
        - Configuration modifications
        - Code changes required
        - Dependencies that need updating
    validations:
      required: false

  - type: input
    id: affected-versions
    attributes:
      label: 📦 Affected Versions
      description: Which versions of Source License are affected?
      placeholder: "All versions, v1.0.0+, specific commit hash, etc."
    validations:
      required: true

  - type: textarea
    id: environment-details
    attributes:
      label: 🖥️ Environment Details
      description: Relevant environment information
      placeholder: |
        - Operating system
        - Ruby version
        - Database type and version
        - Deployment method (development, production)
        - Reverse proxy (nginx, apache)
        - SSL/TLS configuration
    validations:
      required: false

  - type: textarea
    id: discovery-method
    attributes:
      label: 🔎 Discovery Method
      description: How did you discover this vulnerability?
      placeholder: |
        - Manual testing
        - Automated security scanning
        - Code review
        - Security research
        - Incident response
    validations:
      required: false

  - type: checkboxes
    id: responsible-disclosure
    attributes:
      label: 🤝 Responsible Disclosure
      description: Responsible disclosure commitments
      options:
        - label: I will not publicly disclose details until a fix is available (other than this issue)
          required: true
        - label: I will not exploit this vulnerability maliciously
          required: true
        - label: I understand this may be converted to a private security advisory
          required: true

  - type: textarea
    id: additional-context
    attributes:
      label: 📝 Additional Context
      description: Any other relevant information
      placeholder: |
        - References to similar vulnerabilities (CVEs, advisories)
        - Security standards or guidelines violated
        - Recommendations for security testing
        - Contact information for follow-up (optional)
    validations:
      required: false